<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('paises')->insert(['CodPaises' => 'AD', 'Nombre' => 'ANDORRA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AE', 'Nombre' => 'EMIRATOS ÁRABES UNIDOS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AF', 'Nombre' => 'AFGANISTÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AG', 'Nombre' => 'ANTIGUA Y BARBUDA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AI', 'Nombre' => 'ANGUILLA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AL', 'Nombre' => 'ALBANIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AM', 'Nombre' => 'ARMENIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AN', 'Nombre' => 'ANTILLAS HOLANDESAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AO', 'Nombre' => 'ANGOLA ', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AQ', 'Nombre' => 'ANTÁRTIDA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AR', 'Nombre' => 'ARGENTINA', 'idEstado' =>  '1', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AS', 'Nombre' => 'SAMOA AMERICANA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AT', 'Nombre' => 'AUSTRIA ', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AU', 'Nombre' => 'AUSTRALIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AW', 'Nombre' => 'ARUBA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'AZ', 'Nombre' => 'AZERBAYÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BA', 'Nombre' => 'BOSNIA-HERZEGOVINA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BB', 'Nombre' => 'BARBADOS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BD', 'Nombre' => 'BANGLADESH', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BE', 'Nombre' => 'BÉLGICA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BF', 'Nombre' => 'BURKINA FASO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BG', 'Nombre' => 'BULGARIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BH', 'Nombre' => 'BAHRAIN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BI', 'Nombre' => 'BURUNDI', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BJ', 'Nombre' => 'BENÍN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BM', 'Nombre' => 'ISLAS BERMUDAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BN', 'Nombre' => 'BRUNEI DARUSSALAM', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BO', 'Nombre' => 'BOLIVIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BR', 'Nombre' => 'BRASIL', 'idEstado' =>  '1', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BT', 'Nombre' => 'BAHAMAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BS', 'Nombre' => 'BUTÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BV', 'Nombre' => 'ISLAS BUVET', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BW', 'Nombre' => 'BOTSWANA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BY', 'Nombre' => 'BIELORRUSIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'BZ', 'Nombre' => 'BELICE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CA', 'Nombre' => 'CANADÁ', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CC', 'Nombre' => 'ISLA DE COCOS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CD', 'Nombre' => 'REPÚBLICA DEMOCRÁTICA DEL CONGO ', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CF', 'Nombre' => 'REPÚBLICA CENTROAFRICANA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CG', 'Nombre' => 'REPÚBLICA DEL CONGO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CH', 'Nombre' => 'SUIZA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CI', 'Nombre' => 'COSTA DE MARFIL', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CK', 'Nombre' => 'ISLAS COOK', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CL', 'Nombre' => 'CHILE', 'idEstado' =>  '1', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CM', 'Nombre' => 'CAMERÚN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CN', 'Nombre' => 'CHINA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CO', 'Nombre' => 'COLOMBIA', 'idEstado' =>  '1', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CR', 'Nombre' => 'COSTA RICA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CS', 'Nombre' => 'CHECOSLOVAQUIA (ANTIGUO PAÍS)', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CU', 'Nombre' => 'CUBA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CV', 'Nombre' => 'CABO VERDE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CX', 'Nombre' => 'ISLAS CHRISTMAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CY', 'Nombre' => 'CHIPRE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'CZ', 'Nombre' => 'REPÚBLICA CHECA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'DE', 'Nombre' => 'ALEMANIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'DJ', 'Nombre' => 'DJIBOUTI', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'DK', 'Nombre' => 'DINAMARCA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'DM', 'Nombre' => 'DOMINICA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'DO', 'Nombre' => 'REPÚBLICA DOMINICANA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'DZ', 'Nombre' => 'ARGELIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'EC', 'Nombre' => 'ECUADOR', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'EE', 'Nombre' => 'ESTONIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'EG', 'Nombre' => 'EGIPTO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'EH', 'Nombre' => 'SÁHARA OCCIDENTAL', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'ER', 'Nombre' => 'ERITREA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'ES', 'Nombre' => 'ESPAÑA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'ET', 'Nombre' => 'ETIOPÍA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'FI', 'Nombre' => 'FINLANDIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'FJ', 'Nombre' => 'FIJI', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'FK', 'Nombre' => 'ISLAS MALVINAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'FM', 'Nombre' => 'MICRONESIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'FO', 'Nombre' => 'ISLAS FEROE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'FR', 'Nombre' => 'FRANCIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GA', 'Nombre' => 'GABÓN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GD', 'Nombre' => 'GRANADA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GE', 'Nombre' => 'GEORGIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GF', 'Nombre' => 'GUYANA FRANCESA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GG', 'Nombre' => 'GUERNSEY', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GH', 'Nombre' => 'GHANA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GI', 'Nombre' => 'GIBRALTAR', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GL', 'Nombre' => 'GROENLANDIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GM', 'Nombre' => 'GAMBIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GN', 'Nombre' => 'GUINEA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GP', 'Nombre' => 'GUADALUPE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GQ', 'Nombre' => 'GUINEA ECUATORIAL', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GR', 'Nombre' => 'GRECIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GS', 'Nombre' => 'ISLAS GEORGIAS Y SANDWICH DEL SUR', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GT', 'Nombre' => 'GUATEMALA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GU', 'Nombre' => 'GUAM', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GW', 'Nombre' => 'GUINEA-BISSAU', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'GY', 'Nombre' => 'GUAYANA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'HK', 'Nombre' => 'HONG KONG', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'HM', 'Nombre' => 'ISLAS HEARD Y MCDONALD', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'HN', 'Nombre' => 'HONDURAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'HR', 'Nombre' => 'CROACIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'HT', 'Nombre' => 'HAITÍ', 'idEstado' =>  '1', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'HU', 'Nombre' => 'HUNGRÍA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'ID', 'Nombre' => 'INDONESIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'IE', 'Nombre' => 'IRLANDA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'IL', 'Nombre' => 'ISRAEL', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'IM', 'Nombre' => 'ISLA DE MAN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'IN', 'Nombre' => 'INDIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'IO', 'Nombre' => 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'IQ', 'Nombre' => 'IRAQ', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'IR', 'Nombre' => 'IRÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'IS', 'Nombre' => 'ISLANDIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'IT', 'Nombre' => 'ITALIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'JM', 'Nombre' => 'JAMAICA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'JE', 'Nombre' => 'JERSEY', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'JO', 'Nombre' => 'JORDANIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'JP', 'Nombre' => 'JAPÓN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KE', 'Nombre' => 'KENIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KG', 'Nombre' => 'KYRGYSTÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KH', 'Nombre' => 'CAMBOYA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KI', 'Nombre' => 'KIRIBATI', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KM', 'Nombre' => 'ISLAS COMORES', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KN', 'Nombre' => 'SAN KITTS Y NEVIS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KP', 'Nombre' => 'COREA DEL NORTE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KR', 'Nombre' => 'COREA DEL SUR', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KW', 'Nombre' => 'KUWAIT', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KY', 'Nombre' => 'ISLAS CAIMÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'KZ', 'Nombre' => 'KAZAJISTÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LA', 'Nombre' => 'LAOS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LB', 'Nombre' => 'LÍBANO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LC', 'Nombre' => 'SANTA LUCÍA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LI', 'Nombre' => 'LIECHTENSTEIN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LK', 'Nombre' => 'SRI LANKA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LR', 'Nombre' => 'LIBERIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LS', 'Nombre' => 'LESOTO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LT', 'Nombre' => 'LITUANIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LU', 'Nombre' => 'LUXEMBURGO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LV', 'Nombre' => 'LETONIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'LY', 'Nombre' => 'LIBIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MA', 'Nombre' => 'MARRUECOS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MC', 'Nombre' => 'MÓNACO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MD', 'Nombre' => 'MOLDAVIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MG', 'Nombre' => 'MADAGASCAR', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MK', 'Nombre' => 'MACEDONIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MH', 'Nombre' => 'ISLAS MARSHALL', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'ML', 'Nombre' => 'MALI', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MM', 'Nombre' => 'BIRMANIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MN', 'Nombre' => 'MONGOLIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MO', 'Nombre' => 'MACAO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MP', 'Nombre' => 'ISLAS MARIANAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MQ', 'Nombre' => 'MARTINICA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MR', 'Nombre' => 'MAURITANIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MS', 'Nombre' => 'MONTSERRAT', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MT', 'Nombre' => 'MALTA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MU', 'Nombre' => 'MAURICIO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MV', 'Nombre' => 'MALDIVAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MW', 'Nombre' => 'MALAWI', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MX', 'Nombre' => 'MÉXICO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MY', 'Nombre' => 'MALASIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'MZ', 'Nombre' => 'MOZAMBIQUE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NA', 'Nombre' => 'NAMIBIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NC', 'Nombre' => 'NUEVA CALEDONIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NE', 'Nombre' => 'NÍGER', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NF', 'Nombre' => 'ISLAS NORFOLK', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NG', 'Nombre' => 'NIGERIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NI', 'Nombre' => 'NICARAGUA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NL', 'Nombre' => 'PAÍSES BAJOS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NO', 'Nombre' => 'NORUEGA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NP', 'Nombre' => 'NEPAL', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NR', 'Nombre' => 'NAURU', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NT', 'Nombre' => 'ZONA NEUTRAL', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NU', 'Nombre' => 'NIUE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'NZ', 'Nombre' => 'NUEVA ZELANDA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'OM', 'Nombre' => 'OMÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PA', 'Nombre' => 'PANAMÁ', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PE', 'Nombre' => 'PERÚ', 'idEstado' =>  '1', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PF', 'Nombre' => 'POLINESIA FRANCESA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PG', 'Nombre' => 'PAPÚA NUEVA GUINEA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PH', 'Nombre' => 'FILIPINAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PK', 'Nombre' => 'PAKISTÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PL', 'Nombre' => 'POLONIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PM', 'Nombre' => 'SAN PEDRO Y MIQUELÓN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PN', 'Nombre' => 'PITCAIRN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PR', 'Nombre' => 'PUERTO RICO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PS', 'Nombre' => 'TERRITORIOS PALESTINOS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PT', 'Nombre' => 'PORTUGAL', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PW', 'Nombre' => 'PALAU', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'PY', 'Nombre' => 'PARAGUAY', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'QA', 'Nombre' => 'QATAR', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'RE', 'Nombre' => 'ISLA REUNIÓN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'RO', 'Nombre' => 'RUMANÍA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'RU', 'Nombre' => 'RUSIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'RW', 'Nombre' => 'RUANDA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SA', 'Nombre' => 'ARABIA SAUDÍ', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SB', 'Nombre' => 'ISLAS SALOMÓN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SC', 'Nombre' => 'ISLAS SEYCHELLES', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SD', 'Nombre' => 'SUDÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SE', 'Nombre' => 'SUECIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SG', 'Nombre' => 'SINGAPUR', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SH', 'Nombre' => 'SANTA HELENA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SI', 'Nombre' => 'ESLOVENIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SJ', 'Nombre' => 'ISLAS SVALBARD Y JAN MAYENS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SK', 'Nombre' => 'ESLOVAQUIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SL', 'Nombre' => 'SIERRA LEONA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SM', 'Nombre' => 'SAN MARINO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SN', 'Nombre' => 'SENEGAL', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SO', 'Nombre' => 'SOMALIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SR', 'Nombre' => 'SURINAM', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SU', 'Nombre' => 'URSS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'ST', 'Nombre' => 'SANTO TOMÉ Y PRÍNCIPE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SV', 'Nombre' => 'EL SALVADOR', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SY', 'Nombre' => 'SIRIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'SZ', 'Nombre' => 'SUAZILANDIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TC', 'Nombre' => 'ISLAS TURKS Y CAICOS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TD', 'Nombre' => 'CHAD', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TF', 'Nombre' => 'TIERRAS AUSTRALES Y ANTÁRTICAS FRANCESAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TG', 'Nombre' => 'TOGO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TH', 'Nombre' => 'TAILANDIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TJ', 'Nombre' => 'TAYIKISTÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TK', 'Nombre' => 'TOKELAU', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TM', 'Nombre' => 'TURKMENISTÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TN', 'Nombre' => 'TÚNEZ', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TO', 'Nombre' => 'TONGA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TP', 'Nombre' => 'TIMOR ORIENTAL', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TR', 'Nombre' => 'TURQUÍA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TT', 'Nombre' => 'TRINIDAD Y TOBAGO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TV', 'Nombre' => 'TUVALU', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TW', 'Nombre' => 'TAIWÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'TZ', 'Nombre' => 'TANZANIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'UA', 'Nombre' => 'UCRANIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'UG', 'Nombre' => 'UGANDA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'UK', 'Nombre' => 'REINO UNIDO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'UM', 'Nombre' => 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS ', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'US', 'Nombre' => 'ESTADOS UNIDOS DE AMÉRICA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'UY', 'Nombre' => 'URUGUAY', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'UZ', 'Nombre' => 'UZBEKISTÁN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'VA', 'Nombre' => 'VATICANO', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'VC', 'Nombre' => 'SAN VICENTE Y LAS GRANADINAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'VE', 'Nombre' => 'VENEZUELA', 'idEstado' =>  '1', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'VG', 'Nombre' => 'ISLAS VÍRGENES BRITÁNICAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'VI', 'Nombre' => 'ISLAS VÍRGENES AMERICANAS', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'VN', 'Nombre' => 'VIETNAM', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'VU', 'Nombre' => 'VANUATU', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'WF', 'Nombre' => 'ISLAS WALLIS Y FUTUNA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'WS', 'Nombre' => 'SAMOA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'YE', 'Nombre' => 'YEMEN', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'YT', 'Nombre' => 'MAYOTTE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'YU', 'Nombre' => 'YUGOSLAVIA (ANTIGUO PAÍS)', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'ZA', 'Nombre' => 'SUDÁFRICA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'ZM', 'Nombre' => 'ZAMBIA', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'ZR', 'Nombre' => 'ZAIRE (ANTIGUO PAÍS)', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
        DB::table('paises')->insert(['CodPaises' => 'ZW', 'Nombre' => 'ZIMBABWE', 'idEstado' =>  '2', 'created_at' => now()->format('Y-m-d H:i:s'), 'updated_at' => now()->format('Y-m-d H:i:s'),]);
    }
}
